AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template vpc: Create a VPC"

Parameters:
  VPCName:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        - Key: Name
          Value: !Ref VPCName